revolutions_per_second = 0.5
microsteps = "Fullstep"

[[tmc_2209_configs]]
face = "R"
step_pin = 13
dir_pin = 19

[[tmc_2209_configs]]
face = "L"
step_pin = 20
dir_pin = 21

[[tmc_2209_configs]]
face = "U"
step_pin = 17
dir_pin = 27

[[tmc_2209_configs]]
face = "D"
step_pin = 5
dir_pin = 6

[[tmc_2209_configs]]
face = "F"
step_pin = 16
dir_pin = 26

[[tmc_2209_configs]]
face = "B"
step_pin = 2
dir_pin = 3
