revolutions_per_second = 0.5
max_acceleration = 50
microstep_resolution = 1
priority = "Default"

[motors.U]
step_pin = 12
dir_pin = 23
uart_bus = "Uart0"
uart_address = 0

[motors.B]
step_pin = 21
dir_pin = 26
uart_bus = "Uart0"
uart_address = 1

[motors.R]
step_pin = 11
dir_pin = 7
uart_bus = "Uart0"
uart_address = 2

[motors.D]
step_pin = 6
dir_pin = 17
uart_bus = "Uart4"
uart_address = 0

[motors.F]
step_pin = 19
dir_pin = 13
uart_bus = "Uart4"
uart_address = 1

[motors.L]
step_pin = 1
dir_pin = 5
uart_bus = "Uart4"
uart_address = 2
