revolutions_per_second = 0.5
microsteps = "Fullstep"
priority = "Default"

[[tmc_2209_configs]]
face = "R"
step_pin = 11
dir_pin = 7

[[tmc_2209_configs]]
face = "L"
step_pin = 1
dir_pin = 5

[[tmc_2209_configs]]
face = "U"
step_pin = 12
dir_pin = 23

[[tmc_2209_configs]]
face = "D"
step_pin = 6
dir_pin = 17

[[tmc_2209_configs]]
face = "F"
step_pin = 19
dir_pin = 13

[[tmc_2209_configs]]
face = "B"
step_pin = 21
dir_pin = 26
