[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
config = { cargo = { features = "all" }, checkOnSave = { command = "clippy" } }

[[language]]
name = "json"
formatter = { command = "prettierd", args = ["x.json"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettierd", args = ["x.ts"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettierd", args = ["x.js"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettierd", args = ["x.css"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettierd", args = ["x.html"] }
auto-format = true

[[language]]
name = "svelte"
formatter = { command = "prettierd", args = ["x.svelte"] }
auto-format = true

[[language]]
name = "java"
auto-format = true

[language-server.jdtls.config.format]
insertSpaces = true
tabSize = 4

[language-server.tinymist]
config = { exportPdf = "onSave", formatterMode = "typstyle", formatterIndentSize = 4 }

[[language]]
name = "typst"
indent = { unit = "    ", tab-width = 1 }
auto-format = true

[[language]]
name = "c"
indent = { unit = "    ", tab-width = 1 }
auto-format = true

[[language]]
name = "python"
indent = { unit = "    ", tab-width = 1 }
auto-format = true

[language-server.pylsp.config.pylsp]
# plugins.ruff.enabled = true
plugins.black.enabled = true
plugins.rope_autoimport.enabled = true

[[language]]
name = "nix"
formatter.command = "nixfmt"
